server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

    properties:
      hibernate:
        format_sql: false
springdoc:
  swagger-ui:
    csrf:
      enabled: false
  api-docs:
    enabled: false
